version: '3.8'

services:
  # 微服务
  agricultural-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agricultural-service
    ports:
      - "3000:3000"  # api-gateway
      - "3001:3001"  # auth-service
      - "3002:3002"  # user-service
      - "3003:3003"  # diagnosis-service
      - "3004:3004"  # upload-service
      - "3005:3005"  # download-service
      - "3006:3006"  # file-service
      - "3007:3007"  # knowledge-service
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - CONTAINER_MEMORY_LIMIT=16  # 16GB 内存限制
      - CONTAINER_CPU_LIMIT=4      # 4核 CPU 限制
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    restart: unless-stopped
    cpuset: '0,1,2,3'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 8G

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: 