export const AUTH_SERVICE_PORT = 3001;
export const AUTH_SERVICE_NAME = 'AUTH_SERVICE';

export const USER_SERVICE_PORT = 3002;
export const USER_SERVICE_NAME = 'USER_SERVICE';

export const DIAGNOSIS_SERVICE_PORT = 3003;
export const DIAGNOSIS_SERVICE_NAME = 'DIAGNOSIS_SERVICE';

export const UPLOAD_SERVICE_PORT = 3004;
export const UPLOAD_SERVICE_NAME = 'UPLOAD_SERVICE';
