export const AUTH_SERVICE_HTTP_PORT = 3001;
export const AUTH_SERVICE_TCP_PORT = 30001;
export const AUTH_SERVICE_GRPC_PORT = 30011;
export const AUTH_SERVICE_NAME = 'AUTH_SERVICE';
export const AUTH_SERVICE_HOST = '0.0.0.0';

export const USER_SERVICE_HTTP_PORT = 3002;
export const USER_SERVICE_TCP_PORT = 30002;
export const USER_SERVICE_GRPC_PORT = 30012;
export const USER_SERVICE_NAME = 'USER_SERVICE';
export const USER_SERVICE_HOST = '0.0.0.0';

export const DIAGNOSIS_SERVICE_HTTP_PORT = 3003;
export const DIAGNOSIS_SERVICE_TCP_PORT = 30003;
export const DIAGNOSIS_SERVICE_GRPC_PORT = 30013;
export const DIAGNOSIS_SERVICE_NAME = 'DIAGNOSIS_SERVICE';
export const DIAGNOSIS_SERVICE_HOST = '0.0.0.0';

export const UPLOAD_SERVICE_HTTP_PORT = 3004;
export const UPLOAD_SERVICE_TCP_PORT = 30004;
export const UPLOAD_SERVICE_GRPC_PORT = 30014;
export const UPLOAD_SERVICE_NAME = 'UPLOAD_SERVICE';
export const UPLOAD_SERVICE_HOST = '0.0.0.0';

export const DOWNLOAD_SERVICE_HTTP_PORT = 3005;
export const DOWNLOAD_SERVICE_TCP_PORT = 30005;
export const DOWNLOAD_SERVICE_GRPC_PORT = 30015;
export const DOWNLOAD_SERVICE_NAME = 'DOWNLOAD_SERVICE';
export const DOWNLOAD_SERVICE_HOST = '0.0.0.0';

export const FILE_SERVICE_HTTP_PORT = 3006;
export const FILE_SERVICE_TCP_PORT = 30006;
export const FILE_SERVICE_GRPC_PORT = 30016;
export const FILE_SERVICE_NAME = 'FILE_SERVICE';
export const FILE_SERVICE_HOST = '0.0.0.0';

export const KNOWLEDGE_SERVICE_HTTP_PORT = 3007;
export const KNOWLEDGE_SERVICE_TCP_PORT = 30007;
export const KNOWLEDGE_SERVICE_GRPC_PORT = 30017;
export const KNOWLEDGE_SERVICE_NAME = 'KNOWLEDGE_SERVICE';
export const KNOWLEDGE_SERVICE_HOST = '0.0.0.0';
