// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.12.4
// source: apps/api-gateway/src/proto/auth.proto

import { Observable } from 'rxjs';

/* eslint-disable */

export const protobufPackage = 'auth';

/** Auth Service Messages */
export interface RegisterRequest {
  email: string;
  password: string;
}

export interface RegisterResponse {
  success: boolean;
  message: string;
}

export interface LoginRequest {
  login: string;
  password: string;
}

export interface LoginResponse {
  token: string;
  message: string;
}

export interface NotifyRequest {
  email: string;
  link: string;
}

export interface NotifyResponse {
  success: boolean;
  message: string;
}

export interface VerifyRequest {
  token: string;
}

export interface VerifyResponse {
  success: boolean;
  message: string;
}

export interface ButtonsGetRequest {}

export interface ButtonsGetResponse {
  buttons: string[];
}

/** Auth Service */
export interface GrpcAuthService {
  register(request: RegisterRequest): Observable<RegisterResponse>;
  login(request: LoginRequest): Observable<LoginResponse>;
  notify(request: NotifyRequest): Observable<NotifyResponse>;
  verify(request: VerifyRequest): Observable<VerifyResponse>;
  buttonsGet(request: ButtonsGetRequest): Observable<ButtonsGetResponse>;
}
