// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.12.4
// source: apps/api-gateway/src/proto/upload.proto

/* eslint-disable */

export const protobufPackage = 'upload';

/** 文件元数据 */
export interface FileMeta {
  originalname: string;
  mimetype: string;
  size: number;
}

/** 单文件上传请求 */
export interface SaveFileRequest {
  fileMeta: FileMeta;
  fileData: Uint8Array;
  userId: number;
}

/** 单文件上传响应 */
export interface SaveFileResponse {
  success: boolean;
  result: FileInfo | undefined;
}

/** 预加载文件请求 */
export interface PreloadFileRequest {
  fileMd5: string;
  originalFileName: string;
  userId: number;
}

/** 预加载文件响应 */
export interface PreloadFileResponse {
  success: boolean;
  result: FileInfo | undefined;
}

/** 分片上传请求 */
export interface ChunkFileRequest {
  taskMeta: ChunkMeta;
  chunkData: Uint8Array;
}

/** 分片元数据 */
export interface ChunkMeta {
  taskId: string;
  chunkIndex: number;
}

/** 分片上传响应 */
export interface ChunkFileResponse {
  message: string;
  chunkIndex: number;
}

/** 完成上传请求 */
export interface CompleteFileRequest {
  taskId: string;
}

/** 完成上传响应 */
export interface CompleteFileResponse {
  success: boolean;
  file: FileInfo | undefined;
}

/** 创建任务请求 */
export interface CreateTaskRequest {
  userId: number;
  fileName: string;
  fileSize: number;
  fileType: string;
  fileMd5: string;
  totalChunks: number;
}

/** 创建任务响应 */
export interface CreateTaskResponse {
  taskId: string;
  userId: number;
  fileName: string;
  fileSize: number;
  fileType: string;
  fileMd5: string;
  totalChunks: number;
  uploadedChunks: number[];
}

/** 获取任务请求 */
export interface GetTaskRequest {
  taskId: string;
}

/** 获取任务响应 */
export interface GetTaskResponse {
  success: boolean;
  result: CreateTaskResponse | undefined;
}

/** 文件信息 */
export interface FileInfo {
  id: number;
  originalFileName: string;
  storageFileName: string;
  filePath: string;
  fileType: string;
  fileSize: number;
  fileMd5: string;
  access: string;
  version: number;
  createdBy: number;
  updatedBy: number;
  createdAt: string;
  updatedAt: string;
}

export interface GrpcUploadService {
  /** 单文件上传 */
  saveFile(request: SaveFileRequest): Promise<SaveFileResponse>;
  /** 预加载文件 */
  preloadFile(request: PreloadFileRequest): Promise<PreloadFileResponse>;
  /** 分片上传 */
  chunkFile(request: ChunkFileRequest): Promise<ChunkFileResponse>;
  /** 完成上传 */
  completeFile(request: CompleteFileRequest): Promise<CompleteFileResponse>;
  /** 创建任务 */
  createTask(request: CreateTaskRequest): Promise<CreateTaskResponse>;
  /** 获取任务 */
  getTask(request: GetTaskRequest): Promise<GetTaskResponse>;
}
