// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.12.4
// source: apps/api-gateway/src/proto/user.proto

/* eslint-disable */
import { Observable } from 'rxjs';

export const protobufPackage = 'user';

export interface UploadAvatarRequest {
  userId: number;
  /** base64 encoded file data */
  fileData: string;
  mimetype: string;
}

export interface UploadAvatarResponse {
  success: boolean;
  message: string;
}

export interface GetAvatarRequest {
  userId: number;
}

export interface GetAvatarResponse {
  success: boolean;
  message: string;
  metadata?: AvatarMetadata | undefined;
  chunk?: Uint8Array | undefined;
}

export interface AvatarMetadata {
  fileName: string;
  mimeType: string;
  totalSize: number;
}

export interface UserService {
  UploadAvatar(request: UploadAvatarRequest): Observable<UploadAvatarResponse>;
  GetAvatar(request: GetAvatarRequest): Observable<GetAvatarResponse>;
}
