// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.12.4
// source: apps/api-gateway/src/proto/user.proto

import { Observable } from 'rxjs';

/* eslint-disable */

export const protobufPackage = 'user';

/** 基础响应消息 */
export interface BaseResponse {
  code: number;
  message: string;
  data: Uint8Array;
}

/** 时间戳消息 */
export interface Timestamp {
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

/** 角色消息 */
export interface Role {
  id: number;
  name: string;
  alias: string;
  timestamp: Timestamp | undefined;
}

/** 个人信息消息 */
export interface Profile {
  id: number;
  gender: number;
  avatar: string;
  name: string;
  phone: string;
  address: string;
}

/** 用户消息 */
export interface User {
  id: number;
  email: string;
  username: string;
  status: 0 | 1;
  roles: Role[];
  profile: Profile | undefined;
  timestamp: Timestamp | undefined;
}

/** 分页请求 */
export interface PaginationRequest {
  page: number;
  pageSize: number;
}

/** 分页响应 */
export interface PaginationResponse {
  total: number;
  page: number;
  pageSize: number;
}

/** GetProfile 请求 */
export interface GetProfileRequest {
  userId: number;
}

/** GetProfile 响应 */
export interface GetProfileResponse {
  response: BaseResponse | undefined;
}

/** UpdateProfile 请求 */
export interface UpdateProfileRequest {
  userId: number;
  profile: Profile | undefined;
}

/** UpdateProfile 响应 */
export interface UpdateProfileResponse {
  response: BaseResponse | undefined;
}

/** UploadAvatar 请求 */
export interface UploadAvatarRequest {
  userId: number;
  fileData: Uint8Array;
  mimetype: string;
}

/** UploadAvatar 响应 */
export interface UploadAvatarResponse {
  response: BaseResponse | undefined;
}

/** GetAvatar 请求 */
export interface GetAvatarRequest {
  userId: number;
}

/** GetAvatar 响应 */
export interface GetAvatarResponse {
  response: BaseResponse | undefined;
}

/** UpdatePassword 请求 */
export interface UpdatePasswordRequest {
  userId: number;
  confirmPassword: string;
}

/** UpdatePassword 响应 */
export interface UpdatePasswordResponse {
  response: BaseResponse | undefined;
}

/** GetUserList 请求 */
export interface GetUserListRequest {
  pagination: PaginationRequest | undefined;
  username: string;
  name: string;
  phone: string;
  address: string;
}

/** GetUserList 响应 */
export interface GetUserListResponse {
  response: BaseResponse | undefined;
}

/** CreateUser 请求 */
export interface CreateUserRequest {
  user: User | undefined;
  profile: Profile | undefined;
}

/** CreateUser 响应 */
export interface CreateUserResponse {
  response: BaseResponse | undefined;
}

/** GetUser 请求 */
export interface GetUserRequest {
  id: number;
}

/** GetUser 响应 */
export interface GetUserResponse {
  response: BaseResponse | undefined;
}

/** DeleteUser 请求 */
export interface DeleteUserRequest {
  id: number;
}

/** DeleteUser 响应 */
export interface DeleteUserResponse {
  response: BaseResponse | undefined;
}

/** UpdateUser 请求 */
export interface UpdateUserRequest {
  id: number;
  user: User | undefined;
}

/** UpdateUser 响应 */
export interface UpdateUserResponse {
  response: BaseResponse | undefined;
}

/** UpdateUserStatus 请求 */
export interface UpdateUserStatusRequest {
  id: number;
  status: 0 | 1;
}

/** UpdateUserStatus 响应 */
export interface UpdateUserStatusResponse {
  response: BaseResponse | undefined;
}

/** ActivateUser 请求 */
export interface ActivateUserRequest {
  id: number;
}

/** ActivateUser 响应 */
export interface ActivateUserResponse {
  response: BaseResponse | undefined;
}

/** ResetUserPassword 请求 */
export interface ResetUserPasswordRequest {
  id: number;
  password: string;
}

/** ResetUserPassword 响应 */
export interface ResetUserPasswordResponse {
  response: BaseResponse | undefined;
}

/** FindByLogin 请求 */
export interface FindByLoginRequest {
  login: string;
}

/** FindByLogin 响应 */
export interface FindByLoginResponse {
  response: BaseResponse | undefined;
}

/** FindByUsername 请求 */
export interface FindByUsernameRequest {
  username: string;
}

/** FindByUsername 响应 */
export interface FindByUsernameResponse {
  response: BaseResponse | undefined;
}

/** FindByEmail 请求 */
export interface FindByEmailRequest {
  email: string;
}

/** FindByEmail 响应 */
export interface FindByEmailResponse {
  response: BaseResponse | undefined;
}

/** 用户服务 */
export interface UserService {
  /** 获取个人信息 */
  getProfile(request: GetProfileRequest): Observable<GetProfileResponse>;
  /** 更新个人信息 */
  updateProfile(
    request: UpdateProfileRequest,
  ): Observable<UpdateProfileResponse>;
  /** 上传个人头像 */
  uploadAvatar(request: UploadAvatarRequest): Observable<UploadAvatarResponse>;
  /** 获取个人头像 */
  getAvatar(request: GetAvatarRequest): Observable<GetAvatarResponse>;
  /** 修改密码 */
  updatePassword(
    request: UpdatePasswordRequest,
  ): Observable<UpdatePasswordResponse>;
  /** 获取用户列表 */
  getUserList(request: GetUserListRequest): Observable<GetUserListResponse>;
  /** 创建用户 */
  createUser(request: CreateUserRequest): Observable<CreateUserResponse>;
  /** 获取单个用户信息 */
  getUser(request: GetUserRequest): Observable<GetUserResponse>;
  /** 删除用户 */
  deleteUser(request: DeleteUserRequest): Observable<DeleteUserResponse>;
  /** 更新用户 */
  updateUser(request: UpdateUserRequest): Observable<UpdateUserResponse>;
  /** 更新用户状态 */
  updateUserStatus(
    request: UpdateUserStatusRequest,
  ): Observable<UpdateUserStatusResponse>;
  /** 激活用户 */
  activateUser(request: ActivateUserRequest): Observable<ActivateUserResponse>;
  /** 重置用户密码 */
  resetUserPassword(
    request: ResetUserPasswordRequest,
  ): Observable<ResetUserPasswordResponse>;
  /** 根据登录名查找用户 */
  findByLogin(request: FindByLoginRequest): Observable<FindByLoginResponse>;
  /** 根据用户名查找用户 */
  findByUsername(
    request: FindByUsernameRequest,
  ): Observable<FindByUsernameResponse>;
  /** 根据邮箱查找用户 */
  findByEmail(request: FindByEmailRequest): Observable<FindByEmailResponse>;
}
