export enum ConfigEnum {
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_DATABASE = 'DB_DATABASE',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_SYNC = 'DB_SYNC',

  SECRET = 'SECRET',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_RECONNECT = 'REDIS_RECONNECT',
  REDIS_DB = 'REDIS_DB',

  MAIL_HOST = 'MAIL_HOST',
  MAIL_PORT = 'MAIL_PORT',
  MAIL_SECURE = 'MAIL_SECURE',
  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',
  MAIL_FROM = 'MAIL_FROM',

  OSS_ACCESS_KEY_ID = 'OSS_ACCESS_KEY_ID',
  OSS_ACCESS_KEY_SECRET = 'OSS_ACCESS_KEY_SECRET',
  OSS_BUCKET_NAME = 'OSS_BUCKET_NAME',
  OSS_REGION = 'OSS_REGION',

  DIAGNOSIS_INSTANCES = 'DIAGNOSIS_INSTANCES',
  GATEWAY_INSTANCES = 'GATEWAY_INSTANCES',
  OTHER_INSTANCES = 'OTHER_INSTANCES',
}

export enum LogEnum {
  LOG_LEVEL = 'LOG_LEVEL',
  LOG_ON = 'LOG_ON',
  TIMESTAMP = 'TIMESTAMP',
}
